server:
  port: ${PORT:9100}
hostname: ${HOSTNAME:localhost:9100}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka

spring:
  application:
    name: auth-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: "localhost:29092"
          replicationFactor: 1
      bindings:
        createdUserProducer-out-0:
          destination: "user-created"
          content-type: application/json
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
      file-size-threshold: 2MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${BDD_USERNAME:projet-annuel-4}
    password: ${BDD_PASSWORD:password}
    url: jdbc:postgresql://${BDD_URL:localhost:5432/authentication}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${MAIL_USERNAME:annual.projects.4th@gmail.com}
    protocol: smtps
    password: ${MAIL_PASSWORD:tegmijvuymnctfwi}
    port: 465
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:65ebd3de7b3d85fa00f3}
            client-secret: ${GITHUB_CLIENT_SECRET:f64945a0d6e6066bac38230ccca26963590dcb18}
            scope: user:email,read:user
mail:
  debug: true

jwt:
  header: Authorization
  secret:  ${JWT_SECRET:BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY}
  expiration: 86400

recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s
  secret: ${RECAPTCHA_SECRET:6Lc5cLkZAAAAANUjd4--Jx6PioSC_N-9MFKT3PsA}

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.assignment: DEBUG