server:
  port: 9100
hostname: localhost:4200
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    stream:
      kafka:
        binder:
          brokers: "localhost:29092"
          replicationFactor: 1
      bindings:
        createdUserProducer-out-0:
          destination: "user-created"
          content-type: application/json