server:
  port: 9100

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:config-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

      #function:
      # defination: userCreatedOutput
    stream:
      kafka:
        binder:
          brokers: kafka
          replicationFactor: 1
      bindings:
        user-binding-out-0:
          destination: "user-created"
          content-type: application/json